Allow cardinality constraints to be applied to connected elements
FHIR/sushi pull request #1120
Opened 2022-07-19 15:02 UTC by mint-thompson

Completes task [CIMPL-986](https://standardhealthrecord.atlassian.net/browse/CIMPL-986).

When constraining cardinality on an element, if there are connected elements that are the child of a slice, it may be possible to apply the cardinality constraint to those elements. As long as no cardinality is widened, applying the constraints is allowed. This may mean that only the new min or max are applied. If the new cardinality has no overlap with the connected element's existing cardinality, the cardinality constraint can't be applied.

2022-07-19 21:26 UTC, cmoesel requested changes
I think the general concept and approach is good, as it's friendlier than the spurious error we used to give and it's helpful in updating those cardinalities.  When I ran regression, however, some of the changes in one repo didn't make sense to me.

You can reproduce by running regression on `HL7/davinci-pas#master`.  You'll see a bunch of changes in `StructureDefinition-profile-claim-update.json` -- all of which constrain `Claim.supportingInfo:SomeSliceName.extension` to have max `1`.  Here is one example:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/2278253/179850775-830ab03a-53f8-4efe-bc52-26e8231ab8d6.png">

If you look at the FSH definition for that profile, however, you'll see that the only rules on `supportingInfo` are these:
```
* supportingInfo.extension contains InfoChanged named infoChanged 0..1
* supportingInfo.extension[infoChanged] ^short = "A code indicating how the piece of information has changed."
* supportingInfo.modifierExtension contains InfoCancelledFlag named infoCancelledFlag 0..1
* supportingInfo.modifierExtension[infoCancelledFlag] ^short = "Indicates that this piece of information is not to be used."
```
It seems like adding an extension with max `1` (for that specific extension only) is going through and updating the `max` of the non-specific extension element in every slice.  Which is not what it should be doing.

2022-07-27 20:05 UTC, jafeltra submitted a review, later dismissed
This makes sense to me! I have one incredibly small change in a comment, so I'm approving anyway.

2022-07-27 20:05 UTC, jafeltra commented on test/export/StructureDefinitionExporter.test.ts
> +      // * component.interpretation 3..4
How do you feel about this incredibly small fix? Sorry lol
```suggestion
      // * component.interpretation 6..10
```

2022-07-27 20:09 UTC, jafeltra commented
Oh I also ran a full regression again, and there were no differences besides that one sliced element that has the `MS` flag properly applied (which was discussed in Slack).

2022-07-28 18:15 UTC, cmoesel submitted a review, later dismissed
This looks good and works well!  Thanks, @mint-thompson.  I'm approving this, but you probably should accept Julia's minor suggestion before we merge it.

2022-07-28 19:36 UTC, cmoesel approved these changes
Re-approval.  Good work!

2022-07-28 19:36 UTC, merged