Find entities by id, even when their id is set by a rule
FHIR/sushi pull request #1198
Opened 2023-01-23 19:20 UTC by mint-thompson

Fixes #1183 and completes task [CIMPL-1052](https://standardhealthrecord.atlassian.net/browse/CIMPL-1052).

When fishing for most FSH entities, one of the conditions for a match is that the provided string matches the entity's `id`. However, an entity's `id` may be set by one of its rules. To make this more reliable, this PR introduces two main changes:
- All insert rules are applied before any resources are exported.
- When getting the id from a FSH definition, check the rules on the definition for one that sets the `id`.
These two changes together help to make sure that references to resources defined in FSH that have a rule for setting the `id` will resolve correctly.

In addition to the test cases added as part of the PR, the [sample FSH](https://fshschool.org/FSHOnline/#/share/3h1fzck) in the linked issue will now resolve all references correctly.

This change applies only to FSH entities that can be fished up by `id`. This is why `Mapping` is not changed, even though it has an `id`.

2023-01-24 20:02 UTC, cmoesel reviewed
Overall, this looks good and the solution seems like it may help us down the road too!

I made one suggestion and I am currently running a full regression to see if there is any unintended impact.

2023-01-24 21:20 UTC, cmoesel commented
Full regression showed two IGs with differences.  Both are good.

In exhibit A, we see some canonical URLs changed to more properly reflect the correct ID:
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/2278253/214418541-14d007b8-dcef-4f58-a7a7-4f5d659f22fe.png">

In exhibit B, we see some relative references changed to properly include the resourceType. Honestly, I'm not 100% sure why this was affected, but I'll take it:
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/2278253/214418741-e22b1420-b913-4448-b9b3-f569fe356ac5.png">

2023-01-25 18:12 UTC, jafeltra reviewed
This looks really good. I didn't notice anything else beyond Chris's suggestion.

2023-01-25 18:12 UTC, jafeltra commented on src/export/InstanceExporter.ts
> +    instanceDef._instanceMeta.name = fshDefinition.name; // This is name of the instance in the FSH
Lol even though I know what it was like this before, this diff is a little bit funny

2023-01-25 18:12 UTC, jafeltra commented on src/fshtypes/FshCodeSystem.ts
> +    return this._id;
I like this idea!

2023-01-25 19:32 UTC, jafeltra approved these changes
Thanks, Mint! I think this makes sense. I was going back and forth on if it would help to have a `findIdAssignmentRule` function next to the `findIdCaretRule` function with a note that says to change the two together, but they probably are distinct enough that I think it's okay as is. But if you or Chris like the idea, I'm certainly not against it.

I didn't notice anything else!

2023-01-25 21:52 UTC, cmoesel requested changes
Julia suggested creating a `findIdAssignmentRule`. I think that's probably a good idea, because I just found at least one other place that looks for an `id` assignment rule (and it actually isn't as good as yours, @mint-thompson).

So I suggest creating `findIdAssignmentRule` and using it in the relevant location in this PR as well as the other place I found similar code: https://github.com/FHIR/sushi/blob/0238364ea51f97120d79121bc0f41deba210d752/src/fhirtypes/common.ts#L433-L435

Similarly, I also found a place where `findIdCaretRule` can be used: https://github.com/FHIR/sushi/blob/0238364ea51f97120d79121bc0f41deba210d752/src/fhirtypes/mixins.ts#L64-L67

_Also note the use of `_.findLast` above, which seems pretty nice._

2023-01-26 17:04 UTC, cmoesel approved these changes
I like it! Well done!

2023-01-26 17:04 UTC, cmoesel commented on src/fhirtypes/common.ts
> -      const id = idRule?.value ?? instance.id;
Oh... right! We don't even need this anymore. How exciting!

2023-01-26 17:04 UTC, cmoesel commented on src/fhirtypes/mixins.ts
> +      idRule = findIdAssignmentRule(fshDefinition.rules);
Good catch!

2023-01-26 17:34 UTC, jafeltra approved these changes
Looks good to me!

2023-01-26 17:37 UTC, merged