FSH may contain numbers in scientific notation
FHIR/sushi pull request #1203
Opened 2023-02-01 20:08 UTC by mint-thompson

Fixes #1132 and completes task [CIMPL-1001](https://standardhealthrecord.atlassian.net/browse/CIMPL-1001).

A number can be expressed in scientific notation by ending it with "E" followed by the exponent. The "E" can be lower or upper case. The exponent may contain a sign. A negative exponent is indicated by using a minus sign. A positive exponent is indicated by using a plus sign or no sign.

The test case shows a few examples of numbers that are now valid. There are no changes to the application code, only to the lexer definition and the accompanying generated code.

2023-02-03 15:54 UTC, cmoesel requested changes
The grammar change looks good and it passed through full regression with _no changes_.

I noted that the notation doesn't carry through to the JSON in all cases, but I think that's OK. It seems like maybe it only converts to decimal when it can do so with no loss of precision.

The one thing I would like to see is one or two more tests -- specifically in places that accept a regular number (not a quantity).The grammar change looks good and it passed through full regression with _no changes_.

I noted that the notation doesn't carry through to the JSON in all cases, but I think that's OK. It seems like maybe it only converts to decimal when it can do so with no loss of precision.

The one thing I would like to see is a little more testing:
* Using exponents with a few more types (which I think can be done by just adding more `component`s to your existing test
* Using exponents in a fixed value for a profile (ideally a fixed `Quantity` and a fixed `integer`)
* Using exponents in a caret rule (perhaps `^minValueInteger` and/or `^maxValueUnsignedInt` from `ElementDefinition` on an element path)

2023-02-03 15:54 UTC, cmoesel commented on test/import/FSHImporter.test.ts
> +    * component[2].valueQuantity = 6.453E+25 's'
Could you add some more components that test other types that could use exponents?
* `valueInteger` (integer)
* `valueSampledData.period` (decimal)
* `valueSampledData.dimensions` (positiveInt)

2023-02-07 20:29 UTC, mint-thompson commented
@cmoesel Thank you for the feedback! Based on our conversation about handling large values, I've made a small update that should result in more consistent value representations. When an exponent is present, the number is inspected to see if it represents an integer. If it does, a `BigInt` is created. Otherwise, `parseFloat` is used to store the value. The test case should demonstrate the potential combinations.

2023-02-07 21:25 UTC, jafeltra approved these changes
The logic here is trickier than I was expecting, but it makes sense to me! I couldn't think of any cases that would be missed.

2023-02-08 23:00 UTC, cmoesel approved these changes
![image](https://user-images.githubusercontent.com/2278253/217670919-6cafe80b-2119-486c-b9ee-a94c81a06468.png)

2023-02-08 23:01 UTC, merged