Insert rule parameters can be enclosed in double brackets
FHIR/sushi pull request #1216
Opened 2023-02-17 14:48 UTC by mint-thompson

Fixes #1154 and completes task [CIMPL-1054](https://standardhealthrecord.atlassian.net/browse/CIMPL-1054).

When a parameter is enclosed in double brackets, commas and right parentheses do not need to be escaped. The entire parameter value must be enclosed for this feature to be used. Existing insert rules are not affected.

This feature includes changes to the grammar and to the way that `FSHImporter` handles insert rule parameters. I tried to make the grammar changes easier to understand by using fragments. Unfortunately, using tokens for the individual parameters resulted in an ambiguous grammar that would fail to handle most inputs. This is why there is still a lot of work that has to happen in `FSHImporter.parseInsertRuleParams`. That function is where there is the greatest potential for unusual edge cases. I think that the tests I've added should cover those, but please let me know if you think of any important cases that I've missed.

Additionally, there are some changes to `ParamRuleSet` to handle value substitutions enclosed in double brackets. This is done so that long chains of `insert` rules will keep parameter values consistent along the chain. My current implementation may not actually be what we want to go with: it's pretty strict, and doesn't allow for things like `[[{param1} {param2]]`, which maybe it should? Let me know what you think about that one.

2023-03-22 12:59 UTC, cmoesel requested changes
Nice approach to a tricky feature. I think some of the stuff you did here will also be very helpful as we add more capabilities to RuleSets. Thanks!

I've asked a few questions that may (will probably) result in small changes.

As for the regression -- if it's not too difficult, we might consider submitting a PR against VRDR with the fixes, noting that we found this previously undetected issue when we were implementing new features for RuleSet.

2023-03-23 13:50 UTC, mint-thompson commented on src/import/MiniFSHImporter.ts
> +      `\\[\\[{\\s*(${escapedParameters})\\s*}\\]\\]|{\\s*(${escapedParameters})\\s*}`,
Yes, that's correct. Using double-brackets allows you to include leading or trailing space as part of the substituted value.

2023-03-23 14:02 UTC, mint-thompson commented on package.json
> +}
I think that was done automatically by my formatter, so I'll revert it.

2023-03-23 17:29 UTC, cmoesel submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/2278253/227288813-a8f74f0e-bd5d-4f6c-978f-81c725aeb5ac.png)

# Spoiler alert! Double Brackets win!

Nice job, @mint-thompson. I think this will be a very welcome feature for some of our users! Thanks for working through some tough issues!

2023-03-23 17:59 UTC, jafeltra approved these changes
This looks great to me! I couldn't think of any cases you haven't already covered. Yay!

2023-03-24 15:44 UTC, cmoesel requested changes
Just a few tiny things I think can be improved...

2023-03-24 15:44 UTC, cmoesel commented on src/fshtypes/rules/InsertRule.ts
> +        if (/(^\s+)|(\s+$)|[,\)]/g.test(originalParam)) {
I don't think you need to escape `)` in a regex character class (e.g., inside `[` `]`). So this can be: `/(^\s+)|(\s+$)|[,)]/g`

2023-03-24 15:44 UTC, cmoesel commented on src/fshtypes/rules/InsertRule.ts
> +            .replace(/(\]\]\s*)\)/g, '$1\\)')}]]`;
I think you can swap the last two replaces with a single replace by making another capture group:
```ts
.replace(/(\]\]\s*)([,)])/g, '$1\\$2')
```

2023-03-24 15:44 UTC, cmoesel commented on src/fshtypes/rules/InsertRule.ts
> +        // return originalParam.replace(/\\/g, '\\\\').replace(/,/g, '\\,').replace(/\)/g, '\\)');
Is there a reason to keep this commented out code?

2023-03-24 16:55 UTC, cmoesel approved these changes
RE-APPROVED!

2023-03-28 21:23 UTC, merged