Don't create Instances of anything abstract, don't create Profiles of abstract resources
FHIR/sushi pull request #1237
Opened 2023-03-10 18:16 UTC by mint-thompson

Fixes #1218 and completes task [CIMPL-1070](https://standardhealthrecord.atlassian.net/browse/CIMPL-1070).

When exporting an Instance, check if InstanceOf is abstract. If it is, log an error and do not create the Instance.

When exporting a Profile, check if Parent is an abstract resource. If it is, log an error and do not create the Profile. An abstract Profile is allowed as a parent, however.

Remove unused InvalidProfileParentError.

Small updates to existing tests for InstanceExporter and StructureDefinitionExporter so that they are no longer breaking these new rules.

In the small regression set, one repo showed changes. The [fhir-sdoh-clinicalcare](https://github.com/HL7/fhir-sdoh-clinicalcare) IG contains an [Instance](https://github.com/HL7/fhir-sdoh-clinicalcare/blob/bf4880b/input/fsh/instances/SDOHCC-GroupSDOHPatientsForPayerExample.fsh) of an [abstract Profile](https://github.com/HL7/fhir-sdoh-clinicalcare/blob/bf4880b/input/fsh/profiles/SDOHCCGroup.fsh), which now throws an error.

2023-03-14 21:07 UTC, jafeltra approved these changes
Makes sense to me!

2023-03-16 14:47 UTC, cmoesel requested changes
You've implemented the fix for #1218 exactly as it was requested. Unfortunately, I probably should have thought more deeply about #1218 before submitting it.

It comes down to two things, which I elaborated on in individual comments:
* For instances, we only care about the `abstract` status of the `specialization` it is based on (not any profiles that might be in the inheritance chain).
* For profiles, it is actually completely valid to profile an abstract resource.

In doing this, I also noticed that we hard-code `abstract` to `false` when creating profiles (regardless of the parent's `abstract` value). I'm wondering if that is really the right thing to do. I don't know... What do you think?

2023-03-16 18:31 UTC, cmoesel commented on src/export/InstanceExporter.ts
> +    }
Yeah... I think that's fair. We're really just trying to help users detect an issue before they run it through the IG Publisher. So if we miss some, it's not a big deal.

2023-03-17 18:01 UTC, cmoesel approved these changes
You have handled the abstract art of fire well.

![image](https://user-images.githubusercontent.com/2278253/225983163-e93587cc-4871-414f-b09a-1f9fdd452f8b.png)

2023-03-20 19:17 UTC, jafeltra approved these changes
I like it!

2023-03-20 19:17 UTC, jafeltra commented on src/errors/InvalidProfileParentError.ts
I love commenting on a file!

2023-03-20 19:17 UTC, jafeltra commented on test/export/StructureDefinitionExporter.test.ts
We probably don't technically need to update these tests anymore, but the changes are pretty neutral, so it is probably more work than it's worth to revert.

2023-03-21 18:51 UTC, merged