Improve handling of child elements on meta.profile
FHIR/sushi pull request #1353
Opened 2023-09-20 19:28 UTC by mint-thompson

Fixes #1330 and completes task [CIMPL-1169](https://standardhealthrecord.atlassian.net/browse/CIMPL-1169).

An Instance may have extensions or other child elements defined on meta.profile. When these elements exist, they should not interfere with checking for the InstanceOf within the profile array. Additionally, if values are set on meta.profile and on child elements, keep those values at aligned indices when adding InstanceOf to meta.profile.

It sounds sort of complicated when written out, but if you take a look at the test cases I added, I think it makes sense. Please let me know if you think that the behavior I've implemented will cause problems. I ran a 1-year 100-count regression and nothing changed, and I'll go for a bigger set tonight.

(yes, I know the branch says 1159, please forgive me)

2023-09-22 15:24 UTC, mint-thompson commented
Regression update: ran the full one-year regression, no changes.

2023-09-25 16:10 UTC, cmoesel requested changes
I've made one suggestion (which you can take or leave) and a request for some more tests, one of which I think will expose a flaw in keeping `meta.profile` and `meta._profile` in sync.

2023-09-25 16:10 UTC, cmoesel commented on test/export/InstanceExporter.test.ts
> +
Can we add two more tests?
1. Set a different canonical (and extension) directly on `meta.profile[1]` (leaving `meta.profile[0]` empty for SUSHI to put in the default.
2. Set a different canonical at `meta.profile[0]` (w/ the extension) and the instanceOf canonical at `meta.profile[1]` (also w/ the extension). We want to be sure that the depuplication code is working as expected (spoiler alert: I'm pretty sure it's not, see [InstanceExporter.ts#839](https://github.com/FHIR/sushi/blob/e10d628e2534bd07df1b8894c847d1eaec0900be/src/export/InstanceExporter.ts#L839)).

2023-09-29 20:32 UTC, cmoesel approved these changes
This is definitely an improvement on the old behavior. Thank you!

Do you think we should run another regression, just in case?

2023-09-29 20:32 UTC, cmoesel commented on src/export/InstanceExporter.ts
> +        [instanceDef.meta.profile, instanceDef.meta._profile] = unzip(uniqueProfiles);
Wow. What a block of code. Things like this remind me that I should try to keep myself more familiar w/ lodash.

2023-10-03 14:24 UTC, merged