Allow binding to types with the #can-bind characteristic
FHIR/sushi pull request #1363
Opened 2023-09-28 20:08 UTC by jafeltra

Fixes #1347.

This PR makes it so that if a Logical Model includes `#can-bind` included in the `Characteristics` or if it has the `type-characteristics` extension with the `can-bind` value, then that type can have bindings applied to it.

If an element tries to add a binding and is not one of the bindable types and one of the allowed types is a Logical Model, SUSHI will now log a warning. If an element tries to add a binding and it is not a bindable type and none of the types are a Logical Model, SUSHI's original behavior is the same and an error is thrown.

I did update the message in that error to reflect that the type can have a binding if it is a logical model with #can-bind because it seemed to make the error message the most correct, but there technically is not a case when that error message will be logged and the fix will be to add `#can-bind` because that case would case the warning to be logged instead. If you disagree with this approach, let me know.

2023-09-29 21:36 UTC, cmoesel requested changes
Thanks, @jafeltra. This is a nice feature for our users who are working with logical models. I've suggested a few small changes to consider.

As you noted, I think we will want to do some refactoring to simplify this -- but I think that will be a lot easier after we get my upcoming PR in that already refactors some of th code in these areas. So let's get this PR in, then mine, then we can look at refactoring!

2023-09-29 21:36 UTC, cmoesel commented on src/errors/CodedTypeNotFoundError.ts
> +      )}; must be coded (code, Coding, CodeableConcept, Quantity, CodeableReference), the data types (string, uri), or a Logical Model with the #can-bind Characteristic.`
I think you're right to add this to the message (for completeness sake) -- but I suggest tweaking the casing just a bit:
```suggestion
      )}; must be coded (code, Coding, CodeableConcept, Quantity, CodeableReference), the data types (string, uri), or a logical model with the #can-bind characteristic.`
```

2023-09-29 21:36 UTC, cmoesel commented on src/fhirtypes/ElementDefinition.ts
> +    if (isEmpty(validTypes) && !isBindable) {
I'd suggest that `isBindable` should look at the `validTypes` before doing the potentially expensive fishing expedition. In 99.95% of the cases, the requirement for a bindable type will already be fulfilled before we even look at logical models. It also makes `isBindable` complete (i.e., it represents all possibility of the element being bindable).
```suggestion
    const isBindable = validTypes.length || this.type?.some(
      type => fisher?.fishForMetadata(type.code, Type.Logical)?.canBind
    );
    if (!isBindable) {
```

2023-09-29 21:36 UTC, cmoesel commented on src/fhirtypes/ElementDefinition.ts
> +          'Binding on a Logical Model type without the #can-bind Characteristic is discouraged',
I think it's more than discouraged -- it's technically disallowed. Also, it looks like we usually do not capitalize _Logical Model_ in error messages and warnings. So maybe something more like:
```suggestion
          `Bindings can only be applied to logical model types with the #can-bind characteristic. Update the target logical model to declare the #can-bind characteristic or remove the binding from ${this.id}.`,
```

2023-09-29 21:36 UTC, cmoesel commented on src/import/FSHTank.ts
> +          meta.canBind = hasLogicalCharacteristic(result, 'can-bind');
I refactored all this code in the branch I'm currently working on. This will be a fun rebase for me! (But seriously, don't worry about it).

2023-10-02 19:16 UTC, jafeltra commented
Thanks for the feedback @cmoesel. I've taken all your suggestions, but I didn't hit the "commit suggestion" buttons so I could update prettier and the tests for them as well.

2023-10-02 19:23 UTC, cmoesel commented
> I've taken all your suggestions, but I didn't hit the "commit suggestion" buttons so I could update prettier and the tests for them as well.

No problem. I actually prefer it that way. I just use the suggestions feature of GitHub because it makes it very easy to see exactly what I'm suggesting.

I'll re-review when I have a moment.

2023-10-02 19:41 UTC, cmoesel approved these changes
Alright, I like it!

2023-10-03 12:34 UTC, mint-thompson approved these changes
I like the strategy you used to implement this, where you generalized the idea of searching for a specific characteristic. Thank you!

2023-10-03 12:55 UTC, merged