Add logical model entity to FSH grammar
FHIR/sushi pull request #778
Opened 2021-03-15 20:17 UTC by mint-thompson

Completes task [CIMPL-687](https://standardhealthrecord.atlassian.net/browse/CIMPL-687).

For details about logical models, visit the official FHIR documentation: http://hl7.org/fhir/R4/structuredefinition.html.

A logical model is a special kind of StructureDefinition that follows some additional constraints and allows authors to construct more or less arbitrary data structures within FHIR. As such, any FSH rule that can appear on a StructureDefinition can also appear on a logical model. A logical model definition may also contain addElementRules, which allow authors to add new elements to the logical model. This rule incorporates cardinality, flags, and types, allowing for concise definitions in many cases.

There are no test cases associated with this PR, since the importer is not changed. Only the grammar definition and parser contexts are changed as part of this PR.

2021-03-17 15:41 UTC, cmoesel requested changes
Looks good -- I think there are just a could spots that need `resource` added.

2021-03-17 15:41 UTC, cmoesel commented on antlr/src/main/antlr/FSH.g4
> +entity:             alias | profile | extension | invariant | instance | valueSet | codeSystem | ruleSet | paramRuleSet | mapping | logical;
It looks like this needs `resource` too:
```suggestion
entity:             alias | profile | extension | invariant | instance | valueSet | codeSystem | ruleSet | paramRuleSet | mapping | logical | resource;
```

2021-03-17 15:41 UTC, cmoesel commented on src/import/parserContexts.ts
> +  logical(): LogicalContext;
We need `resource()` here too:
```suggestion
  logical(): LogicalContext;
  resource(): ResourceContext;
```

2021-03-17 19:29 UTC, julianxcarter submitted a review, later dismissed
Aside from adding the resource keyword in the spots that Chris pointed out, this looks great to me! Approving preemptively 👍🏽

2021-03-18 14:23 UTC, cmoesel requested changes
Ever so close.  Just one minor tweak and a re-run of the ANTLR code generator is needed.

2021-03-18 14:23 UTC, cmoesel commented on antlr/src/main/antlr/FSH.g4
> +resource:           KW_RESOURCE name sdMetadata lrRule*;
Oops.  Missed this one in my last review.
```suggestion
resource:           KW_RESOURCE name sdMetadata* lrRule*;
```

2021-03-18 14:23 UTC, cmoesel commented on antlr/src/main/antlr/FSH.g4
> +entity:             alias | profile | extension | invariant | instance | valueSet | codeSystem | ruleSet | paramRuleSet | mapping | logical | resource;
b146f0c added `resource` but doesn't show any of the changes I'd expect in the ANTLR-generated files.  I think we need to re-generate those files.

2021-03-18 18:38 UTC, cmoesel approved these changes
This looks good!

2021-03-18 18:38 UTC, cmoesel commented
And @julianxcarter's pre-emptive approval is good enough to justify a merge.

2021-03-18 18:38 UTC, merged