Use HTTPS to download packages
FHIR/sushi pull request #904
Opened 2021-08-17 23:19 UTC by cmoesel

HL7 has turned off HTTP for some package servers -- so now is a good time to switch all our downloads to use HTTPS.  After all, it is just like HTTP but with more S.  We now connect to:
* https://packages.fhir.org
* https://packages2.fhir.org
* https://build.fhir.org

To test this, delete or rename your `~/.fhir` cache then attempt to use SUSHI to build:
* a project based on FHIR 4.0.1 (R4) - should SUCCEED on master and this branch
* a project based on FHIR 4.1.0 (R4B) - should FAIL on master but SUCCEED on this branch
* a project based on FHIR 4.6.0 (R5) - should FAIL on master but SUCCEED on this branch
* a project with a dependency using `current` version - should SUCCEED on master and this branch

2021-08-19 13:27 UTC, ngfreiter requested changes
I'm getting this output when I try to download a package that is current over https:
![image](https://user-images.githubusercontent.com/52747882/130076618-28dee1d2-b7fd-4b6d-9b97-da3022e92431.png)

Now I think there is probably something I could do to make that work, but if it's happening to me, I'm guessing it could happen to many other people on corporate networks, so is this something worth introducing? I also can't say I understand why it happens for `build.fhir.org`, but not for the package servers.

2021-08-19 15:33 UTC, mint-thompson submitted a review, later dismissed

2021-08-19 22:13 UTC, cmoesel commented
OK @ngfreiter - 7b573db contains the error message w/ additional details as we had discussed.

2021-08-20 19:55 UTC, ngfreiter approved these changes
👍

2021-08-23 13:05 UTC, mint-thompson approved these changes

2021-08-23 13:45 UTC, merged